[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/ws/*"
  to = "https://messaging-system-redr.onrender.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200